# Generated by Django 6.0.6 on 2026-06-27 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfoliopage',
            name='theme_accent',
            field=models.CharField(default='dark', max_length=50),
        ),
    ]
