# Generated by Django 6.0.6 on 2026-06-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_portfoliopage_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aisessionlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='portfoliosection',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='portfoliosection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero (Name & Headline)'), ('about', 'About Me Summary'), ('education', 'Educational Background'), ('skills', 'Skills with Levels'), ('projects_grid', 'Featured Projects Grid'), ('contact', 'Contact Action Channel')], max_length=50),
        ),
    ]
