# Generated by Django 5.2.17 on 2026-08-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_otpverification_name_otpverification_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
