# Generated by Django 5.2.17 on 2026-08-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_otpverification_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopage',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='portfoliopage',
            constraint=models.UniqueConstraint(fields=('portfolio', 'slug'), name='unique_page_slug_per_portfolio'),
        ),
    ]
