# Generated by Django 5.2.17 on 2026-08-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_portfoliopage_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
