# Generated by Django 5.0.14 on 2026-09-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_aisessionlog_user_alter_aisessionlog_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero (Name & Headline)'), ('about', 'About Me Summary'), ('education', 'Educational Background'), ('skills', 'Skills with Levels'), ('projects_grid', 'Featured Projects Grid'), ('contact', 'Contact Action Channel'), ('experience', 'Work Experience'), ('services', 'Services & Offerings'), ('testimonials', 'Client Testimonials'), ('certifications', 'Certifications & Awards'), ('stats', 'Key Statistics'), ('blog', 'Blog & Publications')], max_length=50),
        ),
    ]
