# Generated by Django 5.0.14 on 2026-09-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_portfoliosection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='global_bg_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='global_font',
            field=models.CharField(blank=True, default='font-inter', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='global_theme',
            field=models.CharField(blank=True, default='modern_glass', max_length=50),
        ),
    ]
